spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host:
    timeout:
    port:
datasource:
  gmssdk:
    jdbcUrl: jdbc:mysql://192.168.0.133:3306/gms?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 123