server:
  port: 8085
  servlet:
    context-path: /api
spring:
  profiles:
    active: master
  application:
    name: eureka-client-article-service
  boot:
    admin:
      client:
        url: http://localhost:8088
        username: 123
        password: 123
management:
  endpoints:
    web:
      exposure:
        include: '*'
